/**
 * Network Configuration Export
 * Generates real network device configurations from topology data
 * Supports: Cisco IOS, iptables, network documentation
 */
import { NetworkNode, NetworkEdge } from "@/types";
import { DEVICE_TYPES } from "@/lib/network/deviceTypes";

// ============================================================
// Cisco IOS Configuration Generator
// ============================================================

export function generateCiscoIOS(
  nodes: NetworkNode[],
  edges: NetworkEdge[]
): string {
  const lines: string[] = [];

  lines.push("!");
  lines.push("! ============================================");
  lines.push("! Cisco IOS Configuration — Generated by NetVerge");
  lines.push(`! Generated: ${new Date().toISOString()}`);
  lines.push("! ============================================");
  lines.push("!");

  for (const node of nodes) {
    const config = node.data.config;
    const name = sanitizeIOSName(node.data.label);
    const deviceType = node.data.deviceType;

    if (!config.ipAddress) continue;

    lines.push("!");
    lines.push(`! ---- ${node.data.label} (${deviceType}) ----`);
    lines.push("!");

    // Hostname
    lines.push(`hostname ${name}`);

    // Interfaces based on connections
    const nodeEdges = edges.filter(
      (e) => e.source === node.id || e.target === node.id
    );
    let ifaceNum = 0;

    for (const edge of nodeEdges) {
      const peerId = edge.source === node.id ? edge.target : edge.source;
      const peer = nodes.find((n) => n.id === peerId);
      const connType = edge.data?.connectionType || "ethernet";

      let ifName: string;
      if (connType === "fiber") {
        ifName = `GigabitEthernet0/${ifaceNum}`;
      } else if (connType === "wireless") {
        ifName = `Dot11Radio0`;
      } else {
        ifName = `FastEthernet0/${ifaceNum}`;
      }

      lines.push(`interface ${ifName}`);
      if (ifaceNum === 0 && config.ipAddress) {
        lines.push(` ip address ${config.ipAddress} ${config.subnet ? cidrToMask(parseInt(config.subnet.split("/")[1] || "24")) : "255.255.255.0"}`);
        lines.push(` no shutdown`);
      } else {
        lines.push(` no ip address`);
        lines.push(` switchport`);
        lines.push(` no shutdown`);
      }
      lines.push(` description Link to ${peer?.data.label || "Unknown"}`);
      lines.push("!");

      ifaceNum++;
    }

    // VLAN config for switches
    if (
      (deviceType === "l2-switch" || deviceType === "l3-switch") &&
      config.vlan
    ) {
      lines.push(`vlan ${config.vlan}`);
      lines.push(` name VLAN_${config.vlan}`);
      lines.push("!");
    }

    // Routing for routers
    if (deviceType === "router" && config.gateway) {
      lines.push("ip route 0.0.0.0 0.0.0.0 " + config.gateway);
      lines.push("!");
    }

    // Firewall ACL for firewalls
    if (deviceType === "firewall") {
      lines.push("ip access-list extended SECURITY_ACL");
      lines.push(" permit ip any any established");
      lines.push(" deny ip any any log");
      lines.push("!");
      lines.push("interface range FastEthernet0/0 - 1");
      lines.push(" ip access-group SECURITY_ACL in");
      lines.push("!");
    }

    // DNS
    if (deviceType === "dns-server" && config.ipAddress) {
      lines.push("ip name-server " + config.ipAddress);
      lines.push("!");
      lines.push("ip dns server");
      lines.push("!");
    }
  }

  lines.push("!");
  lines.push("end");
  lines.push("!");

  return lines.join("\n");
}

// ============================================================
// iptables Configuration Generator
// ============================================================

export function generateIptables(
  nodes: NetworkNode[],
  edges: NetworkEdge[]
): string {
  const lines: string[] = [];

  lines.push("# ============================================");
  lines.push("# iptables Configuration — Generated by NetVerge");
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push("# ============================================");
  lines.push("");

  const firewalls = nodes.filter((n) => n.data.deviceType === "firewall");
  const servers = nodes.filter(
    (n) =>
      n.data.deviceType === "server" ||
      n.data.deviceType === "database-server" ||
      n.data.deviceType === "application-server"
  );
  const internet = nodes.find(
    (n) => n.data.deviceType === "internet" || n.data.deviceType === "cloud"
  );

  // Find which devices are behind each firewall
  for (const fw of firewalls) {
    const fwConfig = fw.data.config;
    const connectedIds = new Set<string>();

    // Find all devices reachable through this firewall
    const visited = new Set<string>();
    const queue: string[] = [];

    // Start from firewall's connections
    for (const edge of edges) {
      if (edge.source === fw.id) {
        queue.push(edge.target);
        connectedIds.add(edge.target);
      }
      if (edge.target === fw.id) {
        queue.push(edge.source);
        connectedIds.add(edge.source);
      }
    }

    // BFS to find all devices behind firewall
    while (queue.length > 0) {
      const currentId = queue.shift()!;
      if (visited.has(currentId)) continue;
      visited.add(currentId);

      for (const edge of edges) {
        if (edge.source === currentId && !visited.has(edge.target) && edge.target !== fw.id) {
          connectedIds.add(edge.target);
          queue.push(edge.target);
        }
        if (edge.target === currentId && !visited.has(edge.source) && edge.source !== fw.id) {
          connectedIds.add(edge.source);
          queue.push(edge.source);
        }
      }
    }

    const behindFw = nodes.filter((n) => connectedIds.has(n.id));

    lines.push(`# Firewall: ${fw.data.label}`);
    lines.push(`# IP: ${fwConfig.ipAddress || "NOT CONFIGURED"}`);
    lines.push("#");

    // Default policies
    lines.push("# Default policies");
    lines.push("iptables -P INPUT DROP");
    lines.push("iptables -P FORWARD DROP");
    lines.push("iptables -P OUTPUT ACCEPT");
    lines.push("");

    // Allow established connections
    lines.push("# Allow established connections");
    lines.push(
      "iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT"
    );
    lines.push(
      "iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT"
    );
    lines.push("");

    // Allow loopback
    lines.push("# Allow loopback");
    lines.push("iptables -A INPUT -i lo -j ACCEPT");
    lines.push("");

    // Rules for connected servers
    for (const server of behindFw) {
      if (servers.find((s) => s.id === server.id)) {
        const serverConfig = server.data.config;
        if (serverConfig.ipAddress) {
          lines.push(`# ${server.data.label}`);
          if (server.data.deviceType === "database-server") {
            // Database should only be reachable from app servers
            const appServers = behindFw.filter(
              (n) => n.data.deviceType === "application-server"
            );
            for (const app of appServers) {
              if (app.data.config.ipAddress) {
                lines.push(
                  `iptables -A FORWARD -s ${app.data.config.ipAddress} -d ${serverConfig.ipAddress} -p tcp --dport 3306 -j ACCEPT`
                );
              }
            }
            // Deny direct access from outside
            lines.push(
              `iptables -A FORWARD -d ${serverConfig.ipAddress} -p tcp --dport 3306 -j DROP`
            );
          } else {
            // Web / App servers — allow HTTP/HTTPS
            lines.push(
              `iptables -A FORWARD -d ${serverConfig.ipAddress} -p tcp --dport 80 -j ACCEPT`
            );
            lines.push(
              `iptables -A FORWARD -d ${serverConfig.ipAddress} -p tcp --dport 443 -j ACCEPT`
            );
          }
          lines.push("");
        }
      }
    }

    // NAT / Masquerade for internet-facing
    if (internet) {
      const extIface = fwConfig.ipAddress
        ? "eth0"
        : "eth0";
      lines.push("# NAT / Masquerade");
      lines.push(
        `iptables -t nat -A POSTROUTING -o ${extIface} -j MASQUERADE`
      );
      lines.push("echo 1 > /proc/sys/net/ipv4/ip_forward");
      lines.push("");
    }

    lines.push("# Flush rules (cleanup) — uncomment to reset");
    lines.push("# iptables -F");
    lines.push("# iptables -X");
    lines.push("");
  }

  return lines.join("\n");
}

// ============================================================
// ASCII Topology Diagram
// ============================================================

export function generateASCIITopology(
  nodes: NetworkNode[],
  edges: NetworkEdge[]
): string {
  const lines: string[] = [];

  lines.push("╔══════════════════════════════════════════════════════════════╗");
  lines.push("║           Network Topology — NetVerge Export            ║");
  lines.push(`║           Generated: ${new Date().toISOString().slice(0, 19)}               ║`);
  lines.push("╚══════════════════════════════════════════════════════════════╝");
  lines.push("");

  // Build adjacency list
  const adj = new Map<string, string[]>();
  for (const node of nodes) {
    adj.set(node.id, []);
  }
  for (const edge of edges) {
    adj.get(edge.source)?.push(edge.target);
    adj.get(edge.target)?.push(edge.source);
  }

  // Find root (Internet/Cloud)
  const root = nodes.find(
    (n) => n.data.deviceType === "internet" || n.data.deviceType === "cloud"
  );

  if (root) {
    // Tree traversal from root
    const visited = new Set<string>();
    const renderNode = (nodeId: string, prefix: string, isLast: boolean) => {
      if (visited.has(nodeId)) return;
      visited.add(nodeId);

      const node = nodes.find((n) => n.id === nodeId);
      if (!node) return;

      const connector = isLast ? "└── " : "├── ";
      const name = node.data.label;
      const ip = node.data.config.ipAddress || "no ip";
      const type = DEVICE_TYPES[node.data.deviceType]?.label || node.data.deviceType;

      lines.push(`${prefix}${connector}${name} (${type}) [${ip}]`);

      const children = adj.get(nodeId) || [];
      const childPrefix = prefix + (isLast ? "    " : "│   ");
      children.forEach((childId, i) => {
        renderNode(childId, childPrefix, i === children.length - 1);
      });
    };

    lines.push("Network Topology:");
    lines.push("─".repeat(50));
    renderNode(root.id, "", true);
  } else {
    // No root — list all devices
    lines.push("Devices:");
    lines.push("─".repeat(50));
    for (const node of nodes) {
      const ip = node.data.config.ipAddress || "no ip";
      const type = DEVICE_TYPES[node.data.deviceType]?.label || node.data.deviceType;
      const peers = adj.get(node.id) || [];
      const peerNames = peers
        .map((pid) => nodes.find((n) => n.id === pid)?.data.label)
        .filter(Boolean)
        .join(", ");
      lines.push(`  ${node.data.label} (${type}) [${ip}]`);
      if (peerNames) {
        lines.push(`    Connected to: ${peerNames}`);
      }
    }
  }

  // Connection table
  lines.push("");
  lines.push("Connections:");
  lines.push("─".repeat(50));
  lines.push(
    padRight("Source", 20) +
      padRight("Target", 20) +
      padRight("Type", 12) +
      "Status"
  );
  lines.push(
    padRight("─".repeat(19), 20) +
      padRight("─".repeat(19), 20) +
      padRight("─".repeat(11), 12) +
      "─".repeat(8)
  );

  for (const edge of edges) {
    const src = nodes.find((n) => n.id === edge.source);
    const tgt = nodes.find((n) => n.id === edge.target);
    lines.push(
      padRight(src?.data.label || "?", 20) +
        padRight(tgt?.data.label || "?", 20) +
        padRight(edge.data?.connectionType || "ethernet", 12) +
        (edge.data?.status || "active")
    );
  }

  // Device summary
  lines.push("");
  lines.push("Device Summary:");
  lines.push("─".repeat(50));

  const typeCount = new Map<string, number>();
  for (const node of nodes) {
    const typeName = DEVICE_TYPES[node.data.deviceType]?.label || node.data.deviceType;
    typeCount.set(typeName, (typeCount.get(typeName) || 0) + 1);
  }
  for (const [typeName, count] of typeCount) {
    lines.push(`  ${typeName}: ${count}`);
  }
  lines.push(`  Total devices: ${nodes.length}`);
  lines.push(`  Total connections: ${edges.length}`);

  return lines.join("\n");
}

// ============================================================
// Markdown Documentation Export
// ============================================================

export function generateMarkdownDocs(
  nodes: NetworkNode[],
  edges: NetworkEdge[]
): string {
  const lines: string[] = [];

  lines.push("# Network Documentation");
  lines.push("");
  lines.push(`> Generated by NetVerge on ${new Date().toLocaleString()}`);
  lines.push("");

  // Overview
  lines.push("## Overview");
  lines.push("");
  lines.push(`- **Total Devices:** ${nodes.length}`);
  lines.push(`- **Total Connections:** ${edges.length}`);
  lines.push("");

  // Device Table
  lines.push("## Devices");
  lines.push("");
  lines.push("| Device | Type | IP Address | Subnet | VLAN |");
  lines.push("|--------|------|------------|--------|------|");

  for (const node of nodes) {
    const typeName = DEVICE_TYPES[node.data.deviceType]?.label || node.data.deviceType;
    lines.push(
      `| ${node.data.label} | ${typeName} | ${node.data.config.ipAddress || "—"} | ${node.data.config.subnet || "—"} | ${node.data.config.vlan || "—"} |`
    );
  }

  lines.push("");

  // Connections
  lines.push("## Connections");
  lines.push("");
  lines.push("| Source | Target | Type | Bandwidth | Status |");
  lines.push("|--------|--------|------|-----------|--------|");

  for (const edge of edges) {
    const src = nodes.find((n) => n.id === edge.source);
    const tgt = nodes.find((n) => n.id === edge.target);
    lines.push(
      `| ${src?.data.label || "?"} | ${tgt?.data.label || "?"} | ${edge.data?.connectionType || "ethernet"} | ${edge.data?.bandwidth || "—"} | ${edge.data?.status || "active"} |`
    );
  }

  lines.push("");

  // Network Segments
  const subnets = new Map<string, NetworkNode[]>();
  for (const node of nodes) {
    const subnet = node.data.config.subnet;
    if (subnet) {
      if (!subnets.has(subnet)) subnets.set(subnet, []);
      subnets.get(subnet)!.push(node);
    }
  }

  if (subnets.size > 0) {
    lines.push("## Network Segments");
    lines.push("");
    for (const [subnet, subnetNodes] of subnets) {
      lines.push(`### Subnet: ${subnet}`);
      lines.push("");
      for (const node of subnetNodes) {
        lines.push(`- ${node.data.label} — ${node.data.config.ipAddress || "no ip"}`);
      }
      lines.push("");
    }
  }

  // ASCII Diagram
  lines.push("## Topology Diagram");
  lines.push("");
  lines.push("```");
  lines.push(generateASCIITopology(nodes, edges));
  lines.push("```");

  return lines.join("\n");
}

// ============================================================
// Helpers
// ============================================================

function sanitizeIOSName(name: string): string {
  return name.replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase().slice(0, 30);
}

function cidrToMask(cidr: number): string {
  if (cidr < 0 || cidr > 32) return "255.255.255.0";
  const mask = cidr === 0 ? 0 : (~0 << (32 - cidr)) >>> 0;
  return [
    (mask >>> 24) & 0xff,
    (mask >>> 16) & 0xff,
    (mask >>> 8) & 0xff,
    mask & 0xff,
  ].join(".");
}

function padRight(str: string, len: number): string {
  return str.length >= len ? str : str + " ".repeat(len - str.length);
}
